name: meta_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  universal_html: ^2.0.8
  storybook_flutter: ^0.11.2
  video_player: ^2.4.7
  expandable: ^5.0.1

  # Localization
  intl: ^0.17.0

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Data classes
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # State managment
  flutter_bloc: ^8.1.1
  async_redux: ^17.0.0
  rxdart: ^0.27.5

  # Api
  retrofit: ^3.0.1+1
  dio: ^4.0.6

  # Storage
  shared_preferences: ^2.0.15

  # Utils
  useful_extensions: ^0.0.1
  google_fonts: ^3.0.1
  locale_emoji_flutter: ^0.2.1
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  
  # Navigation
  auto_route: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  injectable_generator: ^1.5.4
  dart_code_metrics: ^4.18.3
  retrofit_generator: ^4.0.3+2
  freezed: ^2.1.0+1
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/videos/