name: meta_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cached_network_image: ^3.2.2
  universal_html: ^2.0.8
  storybook_flutter: ^0.11.3
  video_player: ^2.4.7
  expandable: ^5.0.1
  flutter_staggered_grid_view: ^0.6.2
  dropdown_button2: ^1.0.1

  # Localization
  intl: ^0.18.1

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Data classes
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # State managment
  flutter_bloc: ^8.1.1
  async_redux: ^17.0.0
  rxdart: ^0.27.5
  provider: ^6.0.5

  # Api
  retrofit: ^3.0.1+1
  dio: ^4.0.6

  # Storage
  shared_preferences: ^2.0.15

  # Utils
  useful_extensions: ^0.0.1
  google_fonts: ^6.2.1
  locale_emoji_flutter: ^0.2.1
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0
  flutter_portal: ^1.1.3
  pointer_interceptor: ^0.9.3+4
  slider_captcha: ^1.0.0
  flutter_dotenv: ^5.1.0

  # Navigation
  auto_route: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.3.2
  injectable_generator: ^1.5.4

  retrofit_generator: ^4.0.3+2
  freezed: ^2.1.0+1
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/videos/
    - assets/images/crypto/btc.png
    - assets/images/crypto/ethereum.png
    - assets/images/crypto/doge.png
    - assets/images/crypto/bnb.png
    - assets/images/crypto/usdt.png
    - assets/images/crypto/usdc.png
    - assets/images/crypto/dai.png
